name: "Build and Test"

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04] 
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK 8
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Apache Maven (Windows)
        if: ${{ matrix.os == 'windows-2022' }} 
        run: mvn -U clean install -fae -B -Peverything -X -e
      - name: Build with Apache Maven
        if: ${{ matrix.os != 'windows-2022' }} 
        run: mvn -U clean install -Djava.awt.headless=true -fae -B -Peverything -X -e
    env: 
       MAVEN_OPTS: "-Xmx1024M"
